(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const AC = window.AudioContext || window.webkitAudioContext;
  const audioCtx = new AC();
  const state = { A:{file:null,buffer:null}, B:{file:null,buffer:null}, mixed:null, url:null, name:'dual-cab-mix.wav' };
  const controls = ['balance','room','gainA','gainB','hpA','lpA','resA','delayA','panA','hpB','lpB','resB','delayB','panB'];
  const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
  const db=v=>Math.pow(10,v/20);
  const fmtPan=v=>Number(v)===0?'Center':`${Math.abs(Number(v))}% ${Number(v)<0?'L':'R'}`;
  const clean=s=>(s||'IR').replace(/\.[^/.]+$/,'').replace(/[^a-z0-9-_]+/gi,'_').replace(/^_+|_+$/g,'').slice(0,44)||'IR';
  function setStatus(t,w=false){$('status').textContent=t;$('status').style.color=w?'var(--warn)':'var(--muted)'}
  function update(){
    const bal=Number($('balance').value); $('balanceReadout').textContent=bal===0?'50 / 50':bal<0?`${Math.round(50+Math.abs(bal)/2)}% A`:`${Math.round(50+bal/2)}% B`;
    $('roomReadout').textContent=`${$('room').value}%`; $('gainAReadout').textContent=`${Number($('gainA').value).toFixed(1)} dB`; $('gainBReadout').textContent=`${Number($('gainB').value).toFixed(1)} dB`;
    $('hpAReadout').textContent=`${$('hpA').value} Hz`; $('hpBReadout').textContent=`${$('hpB').value} Hz`; $('lpAReadout').textContent=`${(Number($('lpA').value)/1000).toFixed(1)} kHz`; $('lpBReadout').textContent=`${(Number($('lpB').value)/1000).toFixed(1)} kHz`;
    $('resAReadout').textContent=`${Number($('resA').value).toFixed(1)} dB`; $('resBReadout').textContent=`${Number($('resB').value).toFixed(1)} dB`; $('delayAReadout').textContent=`${Number($('delayA').value).toFixed(1).replace('.0','')} ms`; $('delayBReadout').textContent=`${Number($('delayB').value).toFixed(1).replace('.0','')} ms`;
    $('panAReadout').textContent=fmtPan($('panA').value); $('panBReadout').textContent=fmtPan($('panB').value);
    controls.forEach(id=>{const i=$(id); if(!i)return; const p=(Number(i.value)-Number(i.min))/(Number(i.max)-Number(i.min)); const k=i.parentElement.querySelector('.knob'); if(k) k.style.setProperty('--rotation',`${-135+p*270}deg`)});
  }
  function enableKnobs(){
    document.querySelectorAll('.knob-control').forEach(label=>{
      const input=label.querySelector('input[type=range]'), knob=label.querySelector('.knob'); if(!input||!knob)return;
      const fromPointer=e=>{const r=knob.getBoundingClientRect(), cx=r.left+r.width/2, cy=r.top+r.height/2; let a=Math.atan2(e.clientY-cy,e.clientX-cx)*180/Math.PI+90; if(a<-180)a+=360; a=clamp(a,-135,135); const min=+input.min,max=+input.max,step=+input.step||1; input.value=clamp(Math.round((min+(a+135)/270*(max-min))/step)*step,min,max); input.dispatchEvent(new Event('input',{bubbles:true}))};
      knob.addEventListener('pointerdown',e=>{e.preventDefault();knob.setPointerCapture(e.pointerId);fromPointer(e)}); knob.addEventListener('pointermove',e=>{if(e.buttons)fromPointer(e)});
      knob.addEventListener('wheel',e=>{e.preventDefault(); const step=+input.step||1; input.value=clamp(+input.value+(e.deltaY<0?step:-step),+input.min,+input.max); input.dispatchEvent(new Event('input',{bubbles:true}))},{passive:false});
    });
  }
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  async function load(file,ch){
    if(!file)return; setStatus(`Decoding ${file.name}...`);
    try{await audioCtx.resume(); const buf=await audioCtx.decodeAudioData(await file.arrayBuffer()); state[ch]={file,buffer:buf}; $(`fileName${ch}`).textContent=file.name; $(`details${ch}`).innerHTML=[file.name,`${buf.numberOfChannels} ch • ${buf.sampleRate.toLocaleString()} Hz • ${(buf.duration*1000).toFixed(1)} ms`,`${(file.size/1024).toFixed(1)} KB`,'Use delay and polarity for phase alignment.','Resonance adds or removes presence bite.'].map(x=>`<span>${esc(x)}</span>`).join(''); state.mixed=null; revoke(); $('downloadBtn').disabled=$('previewBtn').disabled=true; drawEmpty('IR loaded'); setStatus(`${file.name} loaded. Render the mix when ready.`)}catch(e){console.error(e); setStatus(`Could not decode ${file.name}. Use a valid WAV IR.`,true)}
  }
  function clear(ch){state[ch]={file:null,buffer:null}; $(`file${ch}`).value=''; $(`fileName${ch}`).textContent=ch==='A'?'Load first IR .wav':'Load second IR .wav'; $(`details${ch}`).innerHTML=ch==='A'?'<span>Supported: mono or stereo WAV IRs.</span><span>Nothing leaves your browser.</span>':'<span>Blend two mics, two cabs, or two positions.</span><span>Export the finished mix as a WAV IR.</span>'; state.mixed=null; revoke(); $('downloadBtn').disabled=$('previewBtn').disabled=true; drawEmpty('Channel cleared'); setStatus('Load one or two WAV impulse responses to start.')}
  function val(ch){return{gain:+$(`gain${ch}`).value,hp:+$(`hp${ch}`).value,lp:+$(`lp${ch}`).value,res:+$(`res${ch}`).value,delay:+$(`delay${ch}`).value,pan:+$(`pan${ch}`).value/100,mute:$(`mute${ch}`).checked,solo:$(`solo${ch}`).checked,inv:$(`invert${ch}`).checked}}
  function balance(){const b=+$('balance').value; return b<0?{A:1,B:(100+b)/100}:b>0?{A:(100-b)/100,B:1}:{A:1,B:1}}
  function track(off,ch,c,bfac){
    const s=off.createBufferSource(); s.buffer=state[ch].buffer; const d=off.createDelay(1); d.delayTime.value=c.delay/1000;
    const hp=off.createBiquadFilter(); hp.type='highpass'; hp.frequency.value=c.hp; hp.Q.value=.707;
    const lp=off.createBiquadFilter(); lp.type='lowpass'; lp.frequency.value=c.lp; lp.Q.value=.707;
    const pres=off.createBiquadFilter(); pres.type='peaking'; pres.frequency.value=3600; pres.Q.value=.85; pres.gain.value=c.res;
    const g=off.createGain(); g.gain.value=db(c.gain)*bfac*(c.inv?-1:1); const p=off.createStereoPanner(); p.pan.value=c.pan;
    s.connect(d); d.connect(hp); hp.connect(lp); lp.connect(pres); pres.connect(g); g.connect(p); p.connect(off.destination); s.start(0);
  }
  async function render(){
    const loaded=['A','B'].filter(ch=>state[ch].buffer); if(!loaded.length){setStatus('Load at least one IR before rendering.',true);return}
    $('renderBtn').disabled=true; $('downloadBtn').disabled=$('previewBtn').disabled=true; setStatus('Rendering mix...');
    try{const sr=+$('sampleRate').value, maxDelay=Math.max(+$('delayA').value,+$('delayB').value)/1000, dur=Math.max(...loaded.map(ch=>state[ch].buffer.duration)), room=+$('room').value>0?.06:0, len=Math.max(1,Math.ceil((dur+maxDelay+room+.02)*sr)); const off=new OfflineAudioContext(2,len,sr); const anySolo=['A','B'].some(ch=>val(ch).solo), bal=balance(); loaded.forEach(ch=>{const c=val(ch); if(!c.mute&&(!anySolo||c.solo)) track(off,ch,c,bal[ch])}); let out=await off.startRendering(); out=addRoom(out,+$('room').value); if($('outputMode').value==='mono') out=mono(out); const rep=normalize(out,$('normalize').checked); state.mixed=out; state.name=`${state.A.file?clean(state.A.file.name):'CabA'}__${state.B.file?clean(state.B.file.name):'CabB'}__DualCab_${$('outputMode').value}.wav`; draw(out); setStatus(`${state.name} rendered • ${out.numberOfChannels} ch • ${out.sampleRate.toLocaleString()} Hz • peak ${rep.peakDb} dBFS${rep.norm?' • normalized':''}`); $('downloadBtn').disabled=$('previewBtn').disabled=false}catch(e){console.error(e);setStatus(`Render failed: ${e.message||e}`,true)}finally{$('renderBtn').disabled=false}
  }
  function addRoom(buf,pct){if(pct<=0)return buf; const amt=pct/100,out=audioCtx.createBuffer(buf.numberOfChannels,buf.length,buf.sampleRate), taps=[[7,.12],[13,.08],[22,.052],[35,.032],[51,.018]], orig=[]; for(let ch=0;ch<buf.numberOfChannels;ch++){orig[ch]=new Float32Array(buf.getChannelData(ch)); out.copyToChannel(orig[ch],ch)} taps.forEach(([ms,g])=>{const off=Math.round(buf.sampleRate*ms/1000); for(let ch=0;ch<out.numberOfChannels;ch++){const o=out.getChannelData(ch), src=orig[ch], opp=out.numberOfChannels>1?orig[ch?0:1]:src; for(let i=0;i<buf.length-off;i++) o[i+off]+=(src[i]+opp[i]*.28)*g*amt}}); return out}
  function mono(buf){if(buf.numberOfChannels===1)return buf; const o=audioCtx.createBuffer(1,buf.length,buf.sampleRate), m=o.getChannelData(0), l=buf.getChannelData(0), r=buf.getChannelData(1); for(let i=0;i<buf.length;i++)m[i]=(l[i]+r[i])*.5; return o}
  function normalize(buf,want){let peak=0; for(let ch=0;ch<buf.numberOfChannels;ch++){const d=buf.getChannelData(ch); for(let i=0;i<d.length;i++)peak=Math.max(peak,Math.abs(d[i]))} let norm=false; if(peak>0&&(want||peak>1)){const s=.98/peak; for(let ch=0;ch<buf.numberOfChannels;ch++){const d=buf.getChannelData(ch); for(let i=0;i<d.length;i++)d[i]*=s} peak=.98; norm=true} return{norm,peakDb:peak? (20*Math.log10(peak)).toFixed(2):'-inf'}}
  function wav(buf,bits){const chs=buf.numberOfChannels,sr=buf.sampleRate,n=buf.length,isF=bits==='32f',bit=isF?32:+bits,bps=bit/8,align=chs*bps,bytes=n*align,ab=new ArrayBuffer(44+bytes),v=new DataView(ab); str(v,0,'RIFF'); v.setUint32(4,36+bytes,true); str(v,8,'WAVE'); str(v,12,'fmt '); v.setUint32(16,16,true); v.setUint16(20,isF?3:1,true); v.setUint16(22,chs,true); v.setUint32(24,sr,true); v.setUint32(28,sr*align,true); v.setUint16(32,align,true); v.setUint16(34,bit,true); str(v,36,'data'); v.setUint32(40,bytes,true); const data=Array.from({length:chs},(_,i)=>buf.getChannelData(i)); let o=44; for(let i=0;i<n;i++)for(let ch=0;ch<chs;ch++){const s=clamp(data[ch][i],-1,1); if(isF){v.setFloat32(o,s,true);o+=4}else if(bit===16){v.setInt16(o,s<0?s*0x8000:s*0x7fff,true);o+=2}else{let x=Math.round(s<0?s*0x800000:s*0x7fffff); x=clamp(x,-0x800000,0x7fffff); v.setUint8(o,x&255); v.setUint8(o+1,(x>>8)&255); v.setUint8(o+2,(x>>16)&255); o+=3}} return ab}
  function str(v,o,s){for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))}
  function revoke(){if(state.url){URL.revokeObjectURL(state.url);state.url=null}}
  function download(){if(!state.mixed){setStatus('Render the mix before downloading.',true);return} revoke(); state.url=URL.createObjectURL(new Blob([wav(state.mixed,$('bitDepth').value)],{type:'audio/wav'})); const a=document.createElement('a'); a.href=state.url; a.download=state.name; document.body.appendChild(a); a.click(); a.remove(); setStatus(`Downloaded ${state.name}`)}
  function preview(){if(!state.mixed)return; audioCtx.resume(); const dry=audioCtx.createBuffer(1,Math.floor(audioCtx.sampleRate*.75),audioCtx.sampleRate),d=dry.getChannelData(0); for(let i=0;i<d.length;i++){const t=i/audioCtx.sampleRate, env=Math.exp(-t*12), saw=2*((t*110)%1)-1; d[i]=(saw*.55+Math.sin(2*Math.PI*220*t)*.35+Math.sin(2*Math.PI*440*t)*.18)*env*.45} const s=audioCtx.createBufferSource(), c=audioCtx.createConvolver(), g=audioCtx.createGain(); s.buffer=dry; c.buffer=state.mixed; g.gain.value=.9; s.connect(c); c.connect(g); g.connect(audioCtx.destination); s.start(); setStatus('Auditioning the rendered IR with a short test ping.')}
  function drawEmpty(msg='No rendered IR yet'){const c=$('waveform'),x=c.getContext('2d'); x.clearRect(0,0,c.width,c.height); x.fillStyle='#050608'; x.fillRect(0,0,c.width,c.height); grid(x,c.width,c.height); x.fillStyle='rgba(233,238,241,.62)'; x.font='24px system-ui'; x.textAlign='center'; x.fillText(msg,c.width/2,c.height/2)}
  function draw(buf){const c=$('waveform'),x=c.getContext('2d'),w=c.width,h=c.height; x.clearRect(0,0,w,h); x.fillStyle='#050608'; x.fillRect(0,0,w,h); grid(x,w,h); for(let ch=0;ch<buf.numberOfChannels;ch++){const data=buf.getChannelData(ch),cen=buf.numberOfChannels===1?h/2:ch?h*.68:h*.32,amp=buf.numberOfChannels===1?h*.38:h*.22; x.strokeStyle=ch?'#f7c95c':'#34c4ee'; x.lineWidth=2; x.beginPath(); for(let px=0;px<w;px++){const a=Math.floor(px/w*data.length),b=Math.max(a+1,Math.floor((px+1)/w*data.length)); let mn=1,mx=-1; for(let i=a;i<b;i++){mn=Math.min(mn,data[i]);mx=Math.max(mx,data[i])} x.moveTo(px,cen-mx*amp); x.lineTo(px,cen-mn*amp)} x.stroke()}}
  function grid(x,w,h){x.strokeStyle='rgba(255,255,255,.08)';x.lineWidth=1; for(let i=0;i<=12;i++){x.beginPath();x.moveTo(i*w/12,0);x.lineTo(i*w/12,h);x.stroke()} for(let i=0;i<=4;i++){x.beginPath();x.moveTo(0,i*h/4);x.lineTo(w,i*h/4);x.stroke()}}
  $('fileA').addEventListener('change',e=>load(e.target.files[0],'A')); $('fileB').addEventListener('change',e=>load(e.target.files[0],'B')); $('clearA').onclick=()=>clear('A'); $('clearB').onclick=()=>clear('B'); $('renderBtn').onclick=render; $('downloadBtn').onclick=download; $('previewBtn').onclick=preview; document.querySelectorAll('input,select').forEach(el=>{el.addEventListener('input',update);el.addEventListener('change',update)}); enableKnobs(); update(); drawEmpty();
})();
